# Generated by Django 5.0.6 on 2024-07-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='詳細')),
                ('thumbnail', models.ImageField(upload_to='media/thumbnail', verbose_name='画像')),
                ('movie', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='動画')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('good', models.IntegerField(verbose_name='高評価')),
                ('read', models.IntegerField(verbose_name='閲覧数')),
                ('usertext', models.CharField(max_length=50)),
            ],
        ),
    ]
