# Generated by Django 5.0.6 on 2024-07-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='good',
            field=models.IntegerField(default=0, verbose_name='高評価'),
        ),
        migrations.AlterField(
            model_name='post',
            name='movie',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='動画'),
        ),
        migrations.AlterField(
            model_name='post',
            name='read',
            field=models.IntegerField(default=0, verbose_name='閲覧数'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/thumbnail', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='post',
            name='usertext',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
