# Generated by Django 5.0.6 on 2024-07-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_alter_post_good_alter_post_movie_alter_post_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='movie',
            field=models.FileField(blank=True, null=True, upload_to='media/uploads/%Y/%m/%d/', verbose_name='動画'),
        ),
    ]
